#+TITLE: RNSA - Rotating Neutron Star Analyzer

Rotating Neutron Stars Analyzer (RNSA) is suite for studying rotating neutron star equilibirum
models constructed using RNS v4.0 (unpublished yet).

* The Suite
It contains:

** codor_parser.py
   To submit jobs to HTCondor. It supports a vast range of settings.
** extractor.py
   To produce single tables corresponding to single sequences
** plotter.py
   To plot output.
** instabilizer.py
   To compute turning point models.
** instaplotter.py
   To plot quantities related to the turning points.
** instacomparer.py
* Extra Utilities
Moreover there is a set of utilities:
** cm_colors.py
   To produce the TikZ code to get a rainbow of colors from blue to red.
** eosify.sh
   To convert a EOS table from the RNS v1.1c format to the new RNS v4.0 format
** stardestroyer.sh
   To delete every Output_star folder to save storage
** matplotlibrc
   A simple configuration for having plot's ticks with the siunitx package
** eps_rho_poly.py
   Interactive script to trasform central rest mass density in central energy
   for a polytrope (and reverse).
** dimensionless_cgs.py
   Interactive script to CU units in CGS (and reverse).
** simsync.sh
   Copy the output of a simulation from the remote location to the local one,
   defined in the remote_config file
** watchsim.sh
   Print the current (and continue on updating) log for a remote simulation with
   parameters defined in remote_config
* Requirements
 - Python >= 3.4.0
 - NumPy >= 1.12
 - matplotlib >= 2.0.0
 - matplotlib2tikz >= 0.6.2
 - LaTeX >= 3.14159265
 - gawk >= 4.1.1
 - RNS >= 4.0
 - HTCondor >= 8.4.0
 - rsync >= 3.1.2
* User Guide
  Documentation will be provided.
* License
RNSA is licensed under GNU GPL v3. The full text of the license can be found in
the LICENSE file.
